BIN_LIB=SENDOBJECT

all: build clean

build:
	system "CRTSRCPF FILE($(BIN_LIB)/QSOURCE) RCDLEN(112)"
	
	
	system "CRTRPGMOD  MODULE($(BIN_LIB)SOCKUTILR4) SRCSTMF(SOCKUTILR4.rpgle) "
	
	system "CPYFRMSTMF FROMSTMF('SOCKUTILR4.rpgle') TOMBR('/QSYS.lib/$(BIN_LIB).lib/QSOURCE.file/SOCKUTILR4.mbr') MBROPT(*ADD)"
	
    system "CRTSRVPGM SRVPGM($(BIN_LIB)/SOCKUTILR4) MODULE($(BIN_LIB)/SOCKUTILR4) EXPORT(*SRCFILE) SRCFILE($(BIN_LIB)/QSOURCE)"
                  
	system "CRTBNDDIR  BNDDIR($(BIN_LIB)/SOCKAPI)"
	   
	system "ADDBNDDIRE BNDDIR($(BIN_LIB)/SOCKAPI) OBJ((SOCKUTILR4))"
	
	
	system "CPYFRMSTMF FROMSTMF('ZCLIENT.cmd') TOMBR('/QSYS.lib/$(BIN_LIB).lib/QSOURCE.file/ZCLIENT.mbr') MBROPT(*ADD)"
    system "CRTCMD CMD($(BIN_LIB)/ZCLIENT) PGM($(BIN_LIB)/ZCLIENTRG) SRCFILE($(BIN_LIB)/QSOURCE) SRCMBR(ZCLIENT) REPLACE(*YES)"
	
	system "CPYFRMSTMF FROMSTMF('ZCLIENTCL.clle') TOMBR('/QSYS.lib/$(BIN_LIB).lib/QSOURCE.file/ZCLIENTCL.mbr') MBROPT(*ADD)"
    system "CRTBNDCL PGM($(BIN_LIB)/ZCLIENTCL) SRCFILE($(BIN_LIB)/QSOURCE) SRCMBR(ZCLIENTCL) DFTACTGRP(*NO) ACTGRP(*CALLER) REPLACE(*YES)"
	
	system "CRTSQLRPGI OBJ(ZCLIENTRG) SRCSTMF(ZCLIENTRG.sqlrpgle)"
	
	    
	system "CPYFRMSTMF FROMSTMF('ZSERVER.cmd') TOMBR('/QSYS.lib/$(BIN_LIB).lib/QSOURCE.file/ZSERVER.mbr') MBROPT(*ADD)"
    system "CRTCMD CMD($(BIN_LIB)/ZZERVER) PGM($(BIN_LIB)/ZZERVERRG) SRCFILE($(BIN_LIB)/QSOURCE) SRCMBR(ZSERVER) REPLACE(*YES)"
	
	system "CPYFRMSTMF FROMSTMF('ZSERVERCL.clle') TOMBR('/QSYS.lib/$(BIN_LIB).lib/QSOURCE.file/ZSERVERCL.mbr') MBROPT(*ADD)"
    system "CRTBNDCL PGM($(BIN_LIB)/ZSERVERCL) SRCFILE($(BIN_LIB)/QSOURCE) SRCMBR(ZSERVERCL) DFTACTGRP(*NO) ACTGRP(*CALLER) REPLACE(*YES)"
	
	system "CRTSQLRPGI OBJ(ZSERVERRG) SRCSTMF(ZCLIENTRG.sqlrpgle)"
	
	
clean:
	-system -q "DLTBNDDIR BNDDIR($(BIN_LIB)/SOCKAPI)"
	-system -q "DLTOBJ OBJ($(BIN_LIB)/QSOURCE) OBJTYPE(*FILE)"
	-system -q "DLTOBJ OBJ($(BIN_LIB)/SOCKUTILR4) OBJTYPE(*MODULE)"
	