CREATE OR REPLACE FUNCTION yourlib.returnDurationChar
(
    in_start TIMESTAMP,
    in_end TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
 
 RETURNS CHAR(14)   
 LANGUAGE SQL 
 SPECIFIC yourlib.rtn_dur_c 
 NOT DETERMINISTIC 
 READS SQL DATA 
 CALLED ON NULL INPUT 
 NO EXTERNAL ACTION 
 SET OPTION ALWBLK = *ALLREAD, ALWCPYDTA = *OPTIMIZE, COMMIT = *NONE, DBGVIEW = *SOURCE, DYNUSRPRF = *OWNER, USRPRF = *OWNER   

BEGIN 

 DECLARE duration DECIMAL(10, 4); 
 DECLARE CONTINUE HANDLER FOR SQLEXCEPTION 
 BEGIN 
   RETURN ''; 
 END;

 IF ( in_end IS NULL ) THEN
   RETURN '';
 END IF;

 IF ( in_end < in_start ) THEN
   RETURN '';
 END IF;

 SET duration = DECIMAL(ROUND(in_end - in_start, 4), 10, 4);

 RETURN LEFT(DIGITS(duration), 2) CONCAT ':' CONCAT SUBSTR(DIGITS(duration), 3, 2) CONCAT ':' CONCAT SUBSTR(DIGITS(duration), 5, 2) CONCAT ',' CONCAT RIGHT(DIGITS(duration), 4);

END; 
